<div>
    <section class="content-wrapper">
        <div class="logo-content-wrapper">
        <img src='<?php echo $this->getViewFileUrl('images/footer-logo.svg'); ?>' />
            <p>
                Morbi cursus porttitor enim lobortis molestie. Duis gravida
                turpis dui, eget bibendum magna congue nec.
            </p>
            <p class="contact-links">
                <span><a href="#">(219) 555-0114</a></span> or
                <span
                    ><a href="mailto:proxy@gmail.com">Proxy@gmail.com</a></span
                >
            </p>
        </div>
        <div class="links-wrapper">
            <div class="links-content">
                <h3>My Account</h3>
                <ul>
                    <li><a href="<?php echo $block->getUrl('customer/account'); ?>"> My Account </a></li>
                    <li><a href="<?php echo $block->getUrl('sales/order/history'); ?>"> Order History </a></li>
                    <li><a href="<?php echo $block->getUrl('checkout/cart'); ?>"> Shopping Cart </a></li>
                    <li><a href="<?php echo $block->getUrl('wishlist'); ?>"> Wishlist </a></li>
                </ul>
            </div>
            <div class="links-content">
                <h3>Helps</h3>
                <ul>
                    <li><a href="<?php echo $block->getUrl('contact'); ?>">Contact</a></li>
                    <li><a href="<?php echo $block->getUrl('faq'); ?>">Faqs</a></li>
                    <li><a href="<?php echo $block->getUrl('terms-conditions'); ?>">Terms & Condition</a></li>
                    <li><a href="<?php echo $block->getUrl('privacy-policy-cookie-restriction-mode'); ?>">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="links-content">
                <h3>Proxy</h3>
                <ul>
                    <li><a href="<?php echo $block->getUrl('about-us.html'); ?>">About</a></li>
                    <li><a href="<?php echo $block->getUrl('shop.html'); ?>">Shop</a></li>
                    <li><a href="#">Product</a></li>
                    <li><a href="<?php echo $block->getUrl('sales/order/history'); ?>">Track Order</a></li>
                </ul>
            </div>
            <div class="links-content">
                <h3>Categories</h3>
                <ul>
                    <li><a href="<?php echo $block->getUrl('shop/fresh-fruit.html'); ?>">Fruit & Vegetables</a></li>
                    <li><a href="<?php echo $block->getUrl('shop/meat-and-fish.html'); ?>">Meat & Fish</a></li>
                    <li><a href="<?php echo $block->getUrl('shop/bread-and-bakery.html'); ?>">Bread & Bakery</a></li>
                    <li><a href="<?php echo $block->getUrl('shop/beauty-and-health.html'); ?>">Beauty & Health</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section class="footer-bottom-content">
        <div class="copyright">Ecobazar eCommerce © 2021. All Rights Reserved</div>
        <div class="payments">
            <div class="payment-method">
                <img src="<?php echo $this->getViewFileUrl('images/payments/ApplePay.svg'); ?>" />
            </div>
            <div class="payment-method">
                <img src="<?php echo $this->getViewFileUrl('images/payments/visa-logo.svg'); ?>" />
            </div>
            <div class="payment-method">
                <img src="<?php echo $this->getViewFileUrl('images/payments/Discover.svg'); ?>" />
            </div>
            <div class="payment-method">
                <img src="<?php echo $this->getViewFileUrl('images/payments/Mastercard.svg'); ?>" />
            </div>
            <div class="payment-method">
                <img src="<?php echo $this->getViewFileUrl('images/payments/lock.svg'); ?>" />
            </div>
        </div>
    </section>
</div>

