<div>
    <section class="content-wrapper">
        <div class="logo-content-wrapper">
        <img src='<?php echo $this->getViewFileUrl('images/footer-logo.svg'); ?>' />
            <p>
                Morbi cursus porttitor enim lobortis molestie. Duis gravida
                turpis dui, eget bibendum magna congue nec.
            </p>
            <p class="contact-links">
                <span><a href="#">(219) 555-0114</a></span> or
                <span
                    ><a href="mailto:proxy@gmail.com">Proxy@gmail.com</a></span
                >
            </p>
        </div>
        <div class="links-wrapper">
            <div class="links-content">
                <h3>My Account</h3>
                <ul>
                    <li><a href="#"> My Account </a></li>
                    <li><a href="#"> Order History </a></li>
                    <li><a href="#"> Shoping Cart </a></li>
                    <li><a href="#"> Wishlist </a></li>
                </ul>
            </div>
            <div class="links-content">
                <h3>Helps</h3>
                <ul>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">Faqs</a></li>
                    <li><a href="#">Terms & Condition</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="links-content">
                <h3>Proxy</h3>
                <ul>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Shop</a></li>
                    <li><a href="#">Product</a></li>
                    <li><a href="#">Track Order</a></li>
                </ul>
            </div>
            <div class="links-content">
                <h3>Categories</h3>
                <ul>
                    <li><a href="#">Fruit & Vegetables</a></li>
                    <li><a href="#">Meat & Fish</a></li>
                    <li><a href="#">Bread & Bakery</a></li>
                    <li><a href="#">Beauty & Health</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section class="footer-bottom-content">
        <div class="copyright">Ecobazar eCommerce © 2021. All Rights Reserved</div>
        <div class="payments">
            <img src="<?php echo $this->getViewFileUrl('images/payments/ApplePay.svg'); ?>" />
            <img src="<?php echo $this->getViewFileUrl('images/payments/visa-logo.svg'); ?>" />
            <img src="<?php echo $this->getViewFileUrl('images/payments/Discover.svg'); ?>" />
            <img src="<?php echo $this->getViewFileUrl('images/payments/Mastercard.svg'); ?>" />
            <img src="<?php echo $this->getViewFileUrl('images/payments/lock.svg'); ?>" />
        </div>
    </section>
</div>

