<div class="home-details">
    <div class="details-container">
        <div class="details-image">
            <img src="<?php echo $this->getViewFileUrl('wysiwyg/images/delivery-truck.png'); ?>"/>
        </div>
        <div>
            <h3>Free Shipping</h3>
            <p>Free shipping on all your order</p>
        </div>
    </div>
    <div class="details-container">
        <div class="details-image">
            <img src="<?php echo $this->getViewFileUrl('wysiwyg/images/headphones.png'); ?>"/>
        </div>
        <div>
            <h3>Customer Support 24/7</h3>
            <p>Instant access to Support</p>
        </div>
    </div>
    <div class="details-container">
        <div class="details-image">
            <img src="<?php echo $this->getViewFileUrl('wysiwyg/images/shopping-bag.png'); ?>"/>
        </div>
        <div>
            <h3>100% Secure Payment</h3>
            <p>We ensure your money is save</p>
        </div>
    </div>
    <div class="details-container">
        <div class="details-image">
            <img src="<?php echo $this->getViewFileUrl('wysiwyg/images/package.png'); ?>"/>
        </div>
        <div>
            <h3>Money-Back Guarantee</h3>
            <p>30 Days Money-Back Guarantee</p>
        </div>
    </div>
</div>